const STATUS = ['Backlog','Ready','In Progress','Review','Blocked','Done'];
const TEMPLATES = {
  software:{label:'Software Application',phases:['Discovery','Requirements','UX / Design','Build','Test / QA','Release','Support'],tasks:['Define problem statement','Identify users and stakeholders','Capture requirements','Create data model','Design clickable UI flow','Build MVP features','Test happy path and edge cases','Prepare release notes','Deploy and validate','Capture lessons learned'],risks:['Scope creep','Data migration gaps','Unclear acceptance criteria','Environment/deployment issues']},
  home:{label:'Home Project',phases:['Scope','Budget','Materials','Schedule','Execution','Inspection','Closeout'],tasks:['Define desired outcome','Set budget range','Measure space and constraints','Create materials list','Identify DIY vs contractor work','Order materials','Prepare work area','Complete work package','Inspect final result','Document warranty and lessons'],risks:['Material delays','Cost growth','Permit/inspection delay','Hidden damage']},
  auto:{label:'Auto Project',phases:['Diagnosis','Parts','Tools','Repair Plan','Repair Work','Validation','Maintenance Record'],tasks:['Document symptoms','Research service procedure','Confirm required parts','Confirm required tools','Estimate time and cost','Prepare vehicle safely','Complete repair steps','Test drive or validate','Record parts and mileage','Save lessons learned'],risks:['Incorrect diagnosis','Unavailable parts','Safety issue','Additional repair discovered']},
  work:{label:'Office / Work Project',phases:['Intake','Planning','Coordination','Execution','Reporting','Closeout'],tasks:['Confirm sponsor and outcome','Identify stakeholders','Build WBS','Assign owners','Set milestones','Execute priority tasks','Track issues and risks','Prepare weekly report','Confirm acceptance','Archive project record'],risks:['Stakeholder misalignment','Decision delays','Competing priorities','Unclear ownership']},
  standards:{label:'Document / Standards Project',phases:['Initiation','Draft','Review','Adjudication','Approval','Publication','Maintenance'],tasks:['Define document scope','Identify source materials','Create draft outline','Draft core sections','Conduct internal review','Adjudicate comments','Prepare approval package','Publish baseline','Track change requests','Capture lessons learned'],risks:['Conflicting stakeholder comments','Version control issue','Approval delay','Traceability gaps']},
  event:{label:'Event',phases:['Concept','Venue / Platform','Agenda','Participants','Execution','After Action'],tasks:['Define event purpose','Set date and venue/platform','Create agenda','Invite participants','Prepare materials','Confirm logistics','Run event','Collect feedback','Document outcomes','Close actions'],risks:['Participant availability','Logistics issue','Agenda overrun','Follow-up actions missed']}
};
const DEFAULT = {
  version:'0.1.0',activeView:'dashboard',theme:'light',
  projects:[],activeProjectId:null,archive:[]
};
let state = load();
function uid(prefix='id'){return prefix+'_'+Math.random().toString(36).slice(2,9)}
function today(){return new Date().toISOString().slice(0,10)}
function addDays(date,days){const d=new Date(date);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
function load(){try{return {...DEFAULT,...JSON.parse(localStorage.getItem('thingPlannerState')||'{}')}}catch{return structuredClone(DEFAULT)}}
function save(){localStorage.setItem('thingPlannerState',JSON.stringify(state))}
function toast(msg){const el=document.querySelector('.toast'); if(!el)return; el.textContent=msg; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2200)}
function activeProject(){return state.projects.find(p=>p.id===state.activeProjectId)||state.projects[0]}
function setView(v){state.activeView=v;save();render()}
function setTheme(){state.theme=state.theme==='dark'?'light':'dark';save();render()}
function seedProject(kind='software',name='Demo Project: Thing Planner MVP'){const t=TEMPLATES[kind];const start=today();const team=[{id:uid('user'),name:'Adrian Francis',role:'Owner',email:'echofoxx@gmail.com'},{id:uid('user'),name:'Project Contributor',role:'Editor',email:''}];const phases=t.phases.map((ph,i)=>({id:uid('phase'),name:ph,order:i+1,start:addDays(start,i*7),end:addDays(start,i*7+6)}));let tasks=[];t.tasks.forEach((title,i)=>{const phase=phases[Math.min(Math.floor(i/(Math.ceil(t.tasks.length/phases.length))),phases.length-1)];tasks.push({id:uid('task'),wbs:`${phase.order}.${(tasks.filter(x=>x.phaseId===phase.id).length)+1}`,title,description:`Starter task for ${t.label}. Refine owner, dates, dependencies, and acceptance criteria.`,phaseId:phase.id,milestone:i%3===0,owner:team[i%team.length].name,status:i<2?'Ready':i===2?'In Progress':'Backlog',priority:i%4===0?'High':i%3===0?'Medium':'Normal',start:addDays(start,i*2),due:addDays(start,i*2+5),actualStart:i===2?today():'',actualFinish:'',dependencies:[],checklist:['Define done','Capture evidence','Update status'],evidence:'',comments:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})});const issues=[];const risks=t.risks.map((r,i)=>({id:uid('risk'),type:'Risk',title:r,description:`Potential ${t.label.toLowerCase()} risk. Assign mitigation and owner.`,severity:i===0?'High':'Medium',status:'Open',owner:team[i%team.length].name,linkedTaskId:'',createdAt:today()}));const p={id:uid('project'),name,kind,label:t.label,goal:'Deliver a practical, traceable project outcome with enough structure to manage work professionally.',health:'On Track',start,end:addDays(start,45),team,phases,tasks,issues,risks,decisions:[],lessons:[],activity:[{at:new Date().toISOString(),text:`Project created from ${t.label} template.`}],settings:{workflow:'review-based',budget:false,complexity:'moderate'},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};state.projects.unshift(p);state.activeProjectId=p.id;save();render();toast('Project created')}
function initIfEmpty(){if(!state.projects.length) seedProject('software','Thing Planner MVP Build')}
function pctComplete(p){if(!p||!p.tasks.length)return 0;return Math.round(p.tasks.filter(t=>t.status==='Done').length/p.tasks.length*100)}
function overdue(p){return p.tasks.filter(t=>t.status!=='Done'&&t.due<today()).length}
function dueSoon(p){return p.tasks.filter(t=>t.status!=='Done'&&t.due>=today()&&t.due<=addDays(today(),7)).length}
function health(p){const od=overdue(p);const blocked=p.tasks.filter(t=>t.status==='Blocked').length;if(od>2||blocked>2)return 'At Risk'; if(od||blocked)return 'Watch'; return 'On Track'}
function log(p,text){p.activity.unshift({at:new Date().toISOString(),text});p.updatedAt=new Date().toISOString()}
function layout(content){const p=activeProject();document.documentElement.dataset.theme=state.theme;document.getElementById('app').innerHTML=`<div class="app"><aside class="sidebar"><div class="brand"><div class="logo"></div><div><h1>Thing Planner PM</h1><p>Template-first project command center</p></div></div><div class="nav">${[['dashboard','Command Center'],['wizard','New Project Wizard'],['kanban','Kanban Board'],['wbs','WBS / Task Planner'],['timeline','Timeline'],['logs','Risks / Issues / Decisions'],['reports','Reports'],['archive','Completed Archive']].map(([id,label])=>`<button class="${state.activeView===id?'active':''}" onclick="setView('${id}')">${label}</button>`).join('')}</div><div class="side-card"><h3>Active Project</h3><select onchange="state.activeProjectId=this.value;save();render()">${state.projects.map(x=>`<option value="${x.id}" ${x.id===state.activeProjectId?'selected':''}>${esc(x.name)}</option>`).join('')}</select><p class="small">${p?esc(p.label):'No project yet'}</p></div><div class="side-card"><h3>Quick Actions</h3><div class="grid"><button class="btn" onclick="setTheme()">Toggle Theme</button><button class="btn" onclick="exportJSON()">Export JSON</button><button class="btn" onclick="document.getElementById('importFile').click()">Import JSON</button><button class="btn" onclick="exportCSV()">Export CSV</button></div><input id="importFile" type="file" accept=".json" style="display:none" onchange="importJSON(event)"></div></aside><main class="main"><div class="topbar"><div class="title"><h2>${viewTitle()}</h2><p>${viewSubtitle()}</p></div><div class="actions"><button class="btn primary" onclick="setView('wizard')">+ New Project</button><button class="btn" onclick="openTask()">+ Task</button><button class="btn good" onclick="closeProject()">Close Project</button></div></div>${content}</main><div class="toast"></div><div id="drawer" class="drawer"></div><div id="modal" class="modal"></div></div>`}
function viewTitle(){return {dashboard:'Project Command Center',wizard:'New Project Wizard',kanban:'Kanban Board',wbs:'Work Breakdown Structure',timeline:'Timeline / Gantt',logs:'Traceability Logs',reports:'Reports & Exports',archive:'Completed Project Archive'}[state.activeView]||'Thing Planner PM'}
function viewSubtitle(){return {dashboard:'Simple executive view with enough details to make decisions.',wizard:'Pick a project type and let the app pre-populate phases, milestones, tasks, risks, and a workflow.',kanban:'Drag cards between workflow steps; dates, status, progress, and activity update automatically.',wbs:'Structured plan showing phases, milestones, tasks, owners, dates, and dependencies.',timeline:'Lightweight schedule view for phases and task timing.',logs:'Track issues, risks, decisions, lessons learned, and project change history.',reports:'Generate status reports and export your project for offline work.',archive:'Reuse completed projects as future templates and lessons learned.'}[state.activeView]||''}
function render(){initIfEmpty();const v=state.activeView; if(v==='dashboard')return renderDashboard(); if(v==='wizard')return renderWizard(); if(v==='kanban')return renderKanban(); if(v==='wbs')return renderWBS(); if(v==='timeline')return renderTimeline(); if(v==='logs')return renderLogs(); if(v==='reports')return renderReports(); if(v==='archive')return renderArchive()}
function renderDashboard(){const p=activeProject();const complete=pctComplete(p);const blocked=p.tasks.filter(t=>t.status==='Blocked').length;p.health=health(p);layout(`<div class="grid cols-4"><div class="card metric"><div><div class="label">Complete</div><div class="value">${complete}%</div></div><span class="pill good">${p.health}</span></div><div class="card metric"><div><div class="label">Open Tasks</div><div class="value">${p.tasks.filter(t=>t.status!=='Done').length}</div></div><span class="pill">${p.tasks.length} total</span></div><div class="card metric"><div><div class="label">Due ≤ 7 Days</div><div class="value">${dueSoon(p)}</div></div><span class="pill warn">Focus</span></div><div class="card metric"><div><div class="label">Blocked / Overdue</div><div class="value">${blocked}/${overdue(p)}</div></div><span class="pill danger">Risk</span></div></div><div class="section-head"><h3>${esc(p.name)}</h3><span class="pill">${esc(p.label)}</span></div><div class="card"><p>${esc(p.goal)}</p><div class="progress"><span style="width:${complete}%"></span></div><p class="small">Start ${p.start} · Target ${p.end} · ${p.team.length} team members · ${p.phases.length} phases</p></div><div class="grid cols-2" style="margin-top:16px"><div class="card"><div class="section-head"><h3>AI Next Actions</h3><button class="btn" onclick="aiSuggest()">Refresh</button></div><div id="aiSuggest" class="ai-box">${aiSuggestion(p)}</div></div><div class="card"><h3>Recent Activity</h3><table>${p.activity.slice(0,8).map(a=>`<tr><td>${new Date(a.at).toLocaleString()}</td><td>${esc(a.text)}</td></tr>`).join('')}</table></div></div><div class="section-head"><h3>Priority Work</h3><button class="btn" onclick="setView('kanban')">Open Board</button></div><div class="grid cols-3">${p.tasks.filter(t=>t.status!=='Done').slice(0,6).map(taskCard).join('')}</div>`)}
function renderWizard(){layout(`<div class="card"><h3>Create a new project</h3><p class="small">This is the AI-assisted starter phase. It creates a complete starter plan, then you refine it.</p><div class="form-grid"><label>Project name<input id="newName" value="New Project ${new Date().toLocaleDateString()}"></label><label>Project type<select id="newKind">${Object.entries(TEMPLATES).map(([k,t])=>`<option value="${k}">${t.label}</option>`).join('')}</select></label><label>Complexity<select id="newComplexity"><option>simple</option><option selected>moderate</option><option>complex</option></select></label><label>Workflow<select id="newWorkflow"><option>simple</option><option selected>review-based</option><option>approval-based</option></select></label><label>Target outcome<textarea id="newGoal">Deliver a successful project with clear scope, work breakdown, milestones, owners, risks, and reusable lessons learned.</textarea></label><label>Team members<textarea id="newTeam">Adrian Francis, Owner\nProject Contributor, Editor</textarea></label></div><div class="section-head"><h3>Starter templates</h3></div><div class="grid cols-3">${Object.entries(TEMPLATES).map(([k,t])=>`<div class="card"><h3>${t.label}</h3><p class="small">${t.phases.join(' → ')}</p><button class="btn primary" onclick="createFromWizard('${k}')">Use Template</button></div>`).join('')}</div></div>`)}
function createFromWizard(k){const name=document.getElementById('newName')?.value||'New Project';seedProject(k,name);const p=activeProject();p.goal=document.getElementById('newGoal')?.value||p.goal;p.settings.complexity=document.getElementById('newComplexity')?.value||'moderate';p.settings.workflow=document.getElementById('newWorkflow')?.value||'review-based';const teamRaw=document.getElementById('newTeam')?.value||'';p.team=teamRaw.split('\n').filter(Boolean).map(line=>{const [name,role='Editor']=line.split(',').map(x=>x.trim());return{id:uid('user'),name,role,email:''}});log(p,'AI-assisted wizard generated project phases, tasks, and risks.');save();state.activeView='dashboard';render()}
function renderKanban(){const p=activeProject();layout(`<div class="kanban">${STATUS.map(s=>`<div class="lane" ondragover="event.preventDefault();this.classList.add('drop-hover')" ondragleave="this.classList.remove('drop-hover')" ondrop="dropTask(event,'${s}',this)"><h4>${s}<span>${p.tasks.filter(t=>t.status===s).length}</span></h4>${p.tasks.filter(t=>t.status===s).map(taskCard).join('')||'<div class="empty">Drop tasks here</div>'}</div>`).join('')}</div>`)}
function taskCard(t){return `<div class="task" draggable="true" ondragstart="event.dataTransfer.setData('text/plain','${t.id}')" onclick="openTask('${t.id}')"><h5>${esc(t.wbs||'')} ${esc(t.title)}</h5><p>${esc(t.description||'')}</p><div class="task-meta"><span class="pill">${esc(t.owner||'Unassigned')}</span><span class="pill ${t.priority==='High'?'danger':t.priority==='Medium'?'warn':''}">${esc(t.priority||'Normal')}</span><span class="pill">Due ${t.due||'TBD'}</span></div></div>`}
function dropTask(e,status,lane){lane.classList.remove('drop-hover');const id=e.dataTransfer.getData('text/plain');const p=activeProject();const t=p.tasks.find(x=>x.id===id);if(!t)return;const old=t.status;t.status=status;t.updatedAt=new Date().toISOString();if(status==='In Progress'&&!t.actualStart)t.actualStart=today();if(status==='Done'&&!t.actualFinish)t.actualFinish=today();if(status==='Blocked'){const reason=prompt('Why is this task blocked?','Waiting on decision / dependency');if(reason)t.comments.push({at:new Date().toISOString(),text:`Blocked: ${reason}`})}log(p,`Task "${t.title}" moved from ${old} to ${status}.`);save();renderKanban()}
function renderWBS(){const p=activeProject();layout(`<div class="card"><div class="section-head"><h3>Task Plan</h3><button class="btn" onclick="openTask()">+ Add Task</button></div><table><thead><tr><th>WBS</th><th>Task</th><th>Phase</th><th>Owner</th><th>Status</th><th>Priority</th><th>Start</th><th>Due</th></tr></thead><tbody>${p.tasks.sort((a,b)=>(a.wbs||'').localeCompare(b.wbs||'',undefined,{numeric:true})).map(t=>`<tr onclick="openTask('${t.id}')"><td>${esc(t.wbs)}</td><td><b>${esc(t.title)}</b><br><span class="small">${esc(t.description)}</span></td><td>${esc((p.phases.find(ph=>ph.id===t.phaseId)||{}).name||'')}</td><td>${esc(t.owner)}</td><td>${esc(t.status)}</td><td>${esc(t.priority)}</td><td>${t.start||''}</td><td>${t.due||''}</td></tr>`).join('')}</tbody></table></div>`)}
function renderTimeline(){const p=activeProject();const start=new Date(p.start), end=new Date(p.end);const total=Math.max(1,(end-start)/86400000);layout(`<div class="card"><h3>Project Timeline</h3><p class="small">Baseline-style visualization. Drag/drop and task edits keep this synced.</p><div class="timeline">${p.tasks.map(t=>{const s=new Date(t.start||p.start),d=new Date(t.due||p.end);const left=Math.max(0,Math.min(100,((s-start)/86400000)/total*100));const width=Math.max(4,Math.min(100-left,((d-s)/86400000)/total*100));return `<div class="bar-row"><div><b>${esc(t.wbs)} ${esc(t.title)}</b><br><span class="small">${esc(t.owner)} · ${esc(t.status)}</span></div><div class="bar-track"><div class="bar" style="left:${left}%;width:${width}%"></div></div></div>`}).join('')}</div></div>`)}
function renderLogs(){const p=activeProject();const sections=[['risks','Risks'],['issues','Issues'],['decisions','Decisions'],['lessons','Lessons Learned']];layout(`<div class="grid cols-2">${sections.map(([key,label])=>`<div class="card"><div class="section-head"><h3>${label}</h3><button class="btn" onclick="addLog('${key}')">+ Add</button></div><table>${(p[key]||[]).map(x=>`<tr><td><b>${esc(x.title)}</b><br><span class="small">${esc(x.description||'')}</span></td><td><span class="pill">${esc(x.status||x.severity||'Open')}</span></td></tr>`).join('')||`<tr><td class="empty">No ${label.toLowerCase()} yet</td></tr>`}</table></div>`).join('')}</div><div class="card" style="margin-top:16px"><h3>Change / Activity Log</h3><table>${p.activity.map(a=>`<tr><td>${new Date(a.at).toLocaleString()}</td><td>${esc(a.text)}</td></tr>`).join('')}</table></div>`)}
function addLog(key){const p=activeProject();const title=prompt(`New ${key.slice(0,-1)} title`);if(!title)return;const description=prompt('Description / note','');p[key].unshift({id:uid(key),title,description,status:'Open',severity:'Medium',createdAt:today()});log(p,`Added ${key.slice(0,-1)}: ${title}`);save();renderLogs()}
function renderReports(){const p=activeProject();const report=generateReport(p);layout(`<div class="grid cols-2"><div class="card"><h3>Status Report</h3><div class="report">${esc(report)}</div><div class="split" style="margin-top:12px"><button class="btn" onclick="copyReport()">Copy Report</button><button class="btn" onclick="downloadText('project-status-report.md',generateReport(activeProject()))">Download Markdown</button></div></div><div class="card"><h3>Import / Export</h3><p>Use JSON for full offline continuation. Use CSV for spreadsheet review of tasks.</p><button class="btn primary" onclick="exportJSON()">Export Full Project JSON</button> <button class="btn" onclick="exportCSV()">Export Tasks CSV</button><hr><p class="small">JSON import replaces/merges the app state from a prior export. CSV export includes tasks, status, WBS, owners, dates, and phases.</p><h3>Project Health</h3><div class="progress"><span style="width:${pctComplete(p)}%"></span></div><p>${pctComplete(p)}% complete · ${overdue(p)} overdue · ${p.risks.filter(r=>r.status==='Open').length} open risks</p></div></div>`)}
function renderArchive(){layout(`<div class="grid cols-2">${state.archive.map(p=>`<div class="card"><h3>${esc(p.name)}</h3><p class="small">${esc(p.label)} · closed ${p.closedAt?.slice(0,10)||''}</p><p>${esc(p.closeout?.summary||'No summary captured.')}</p><button class="btn" onclick="reuseArchive('${p.id}')">Reuse as Template</button></div>`).join('')||'<div class="empty">No completed projects archived yet.</div>'}</div>`)}
function openTask(id){const p=activeProject();let t=id?p.tasks.find(x=>x.id===id):{id:'',wbs:'',title:'',description:'',phaseId:p.phases[0]?.id,owner:p.team[0]?.name,status:'Backlog',priority:'Normal',start:today(),due:addDays(today(),7),checklist:[],comments:[]};document.getElementById('drawer').innerHTML=`<div class="section-head"><h3>${id?'Task Details':'New Task'}</h3><button class="btn" onclick="closeDrawer()">Close</button></div><label>WBS<input id="taskWbs" value="${esc(t.wbs||'')}"></label><label>Title<input id="taskTitle" value="${esc(t.title||'')}"></label><label>Description<textarea id="taskDesc">${esc(t.description||'')}</textarea></label><div class="form-grid"><label>Phase<select id="taskPhase">${p.phases.map(ph=>`<option value="${ph.id}" ${ph.id===t.phaseId?'selected':''}>${esc(ph.name)}</option>`).join('')}</select></label><label>Owner<select id="taskOwner">${p.team.map(u=>`<option ${u.name===t.owner?'selected':''}>${esc(u.name)}</option>`).join('')}</select></label><label>Status<select id="taskStatus">${STATUS.map(s=>`<option ${s===t.status?'selected':''}>${s}</option>`).join('')}</select></label><label>Priority<select id="taskPriority">${['Low','Normal','Medium','High'].map(s=>`<option ${s===t.priority?'selected':''}>${s}</option>`).join('')}</select></label><label>Start<input id="taskStart" type="date" value="${t.start||''}"></label><label>Due<input id="taskDue" type="date" value="${t.due||''}"></label></div><label>Evidence / Completion Notes<textarea id="taskEvidence">${esc(t.evidence||'')}</textarea></label><div class="split"><button class="btn primary" onclick="saveTask('${id||''}')">Save Task</button>${id?`<button class="btn danger" onclick="deleteTask('${id}')">Delete</button>`:''}</div><hr><h3>Comments</h3>${(t.comments||[]).map(c=>`<p class="small"><b>${new Date(c.at).toLocaleString()}</b><br>${esc(c.text)}</p>`).join('')}`;document.getElementById('drawer').classList.add('show')}
function closeDrawer(){document.getElementById('drawer').classList.remove('show')}
function saveTask(id){const p=activeProject();let t=id?p.tasks.find(x=>x.id===id):null;if(!t){t={id:uid('task'),checklist:[],comments:[],createdAt:new Date().toISOString()};p.tasks.push(t)}const old=t.status;t.wbs=v('taskWbs');t.title=v('taskTitle')||'Untitled Task';t.description=v('taskDesc');t.phaseId=v('taskPhase');t.owner=v('taskOwner');t.status=v('taskStatus');t.priority=v('taskPriority');t.start=v('taskStart');t.due=v('taskDue');t.evidence=v('taskEvidence');t.updatedAt=new Date().toISOString();if(t.status==='In Progress'&&!t.actualStart)t.actualStart=today();if(t.status==='Done'&&!t.actualFinish)t.actualFinish=today();log(p,`${id?'Updated':'Created'} task: ${t.title}${old&&old!==t.status?` (${old} → ${t.status})`:''}.`);save();closeDrawer();render()}
function deleteTask(id){const p=activeProject();const t=p.tasks.find(x=>x.id===id);if(!confirm(`Delete task ${t?.title}?`))return;p.tasks=p.tasks.filter(x=>x.id!==id);log(p,`Deleted task: ${t?.title}`);save();closeDrawer();render()}
function v(id){return document.getElementById(id)?.value||''}
function aiSuggestion(p){const blocked=p.tasks.filter(t=>t.status==='Blocked');const next=p.tasks.filter(t=>['Ready','In Progress'].includes(t.status)).slice(0,3);if(blocked.length)return `<b>Resolve blockers first.</b><br>${blocked.map(t=>`• ${esc(t.title)}: add owner, reason, and next decision.`).join('<br>')}`;if(overdue(p))return `<b>Recover schedule.</b><br>${overdue(p)} task(s) are overdue. Move them to Review/Done if complete, or reset dates with a note.`;return `<b>Recommended focus:</b><br>${next.map(t=>`• ${esc(t.title)} due ${t.due}`).join('<br>')||'Create the next set of Ready tasks.'}<br><br><span class="small">AI mode is currently local rule-based. Roadmap includes Ollama/API-backed plan generation.</span>`}
function aiSuggest(){document.getElementById('aiSuggest').innerHTML=aiSuggestion(activeProject())}
function generateReport(p){return `# ${p.name} Status Report\n\nHealth: ${health(p)}\nProgress: ${pctComplete(p)}% complete\nPeriod: ${p.start} to ${p.end}\n\n## Summary\n${p.goal}\n\n## Key Metrics\n- Total tasks: ${p.tasks.length}\n- Done: ${p.tasks.filter(t=>t.status==='Done').length}\n- In progress: ${p.tasks.filter(t=>t.status==='In Progress').length}\n- Blocked: ${p.tasks.filter(t=>t.status==='Blocked').length}\n- Overdue: ${overdue(p)}\n- Open risks: ${p.risks.filter(r=>r.status==='Open').length}\n\n## Next Actions\n${p.tasks.filter(t=>t.status!=='Done').slice(0,5).map(t=>`- ${t.title} — ${t.owner}, due ${t.due}, status ${t.status}`).join('\n')||'- No open tasks.'}\n\n## Risks / Issues\n${[...p.risks,...p.issues].slice(0,6).map(r=>`- ${r.title}: ${r.description||''}`).join('\n')||'- No open risks or issues captured.'}\n\n## Recent Activity\n${p.activity.slice(0,6).map(a=>`- ${new Date(a.at).toLocaleDateString()}: ${a.text}`).join('\n')}`}
function copyReport(){navigator.clipboard.writeText(generateReport(activeProject()));toast('Report copied')}
function exportJSON(){downloadText(`thing-planner-${activeProject().name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.json`,JSON.stringify({exportedAt:new Date().toISOString(),state},null,2))}
function importJSON(e){const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(data.state)state=data.state;else if(data.projects)state={...DEFAULT,...data};save();render();toast('Imported JSON')}catch(err){alert('Invalid JSON import')}};reader.readAsText(file)}
function csvCell(x){return `"${String(x??'').replaceAll('"','""')}"`}
function exportCSV(){const p=activeProject();const rows=[['Project','WBS','Task','Description','Phase','Owner','Status','Priority','Start','Due','Actual Start','Actual Finish']];p.tasks.forEach(t=>rows.push([p.name,t.wbs,t.title,t.description,(p.phases.find(ph=>ph.id===t.phaseId)||{}).name,t.owner,t.status,t.priority,t.start,t.due,t.actualStart,t.actualFinish]));downloadText(`thing-planner-${p.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}-tasks.csv`,rows.map(r=>r.map(csvCell).join(',')).join('\n'))}
function downloadText(name,text){const blob=new Blob([text],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function closeProject(){const p=activeProject();const summary=prompt('Closeout summary / lesson learned','Project completed successfully. Reuse the task plan and lessons for similar projects.');if(summary===null)return;p.closeout={summary,completePct:pctComplete(p),finalHealth:health(p)};p.closedAt=new Date().toISOString();state.archive.unshift(structuredClone(p));state.projects=state.projects.filter(x=>x.id!==p.id);state.activeProjectId=state.projects[0]?.id||null;if(!state.projects.length)seedProject('work','New Work Project');save();render();toast('Project archived')}
function reuseArchive(id){const a=state.archive.find(x=>x.id===id);if(!a)return;const p=structuredClone(a);p.id=uid('project');p.name=`${a.name} - Reused`;p.createdAt=new Date().toISOString();p.updatedAt=p.createdAt;p.closedAt=null;p.closeout=null;p.tasks.forEach(t=>{t.id=uid('task');t.status=t.status==='Done'?'Backlog':t.status;t.actualStart='';t.actualFinish=''});p.activity=[{at:new Date().toISOString(),text:`Reused completed project template from ${a.name}.`}];state.projects.unshift(p);state.activeProjectId=p.id;save();state.activeView='dashboard';render()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
window.addEventListener('load',render);
